### ISSUE TITLE
Blank Screen After Setting Glorious Greeter as Login Page

### ISSUE THREAD

**Issue by jordanenrico** [VaughnValle/lush-pop#1]
> Pop! OS 20.10
> KDE Plasma 5.19.5
> KDE Frameworks 5.74
> Qt 5.14.2
> LightDM 1.30
> LightDM Webkit2 2.2.5
> Glorious Theme 2.0.5

Hi, I am having a problem installing Glorious webkit2 greeter (Last part of the video). After rebooting, the greeter turns entirely blank with my cursor sometimes flickering. I have to use CLI to revert that back to the original greeter. To confirm that the problem is most likely at the theme itself instead of the lightdm, I set `greeter-session` variable in `/etc/lightdm/lightdm.conf.d/lightdm.conf` to `unity-greeter` instead of `lightdm-webkit2-greeter`. It turns out to be running smoothly using Antergros Greeter.

Has anyone faces this issue? Any recommendation on how to solve it? Thanks in advance !

**Comment by VaughnValle** [comment]
The Glorious theme is pretty outdated as this point. Install the latest version here: https://github.com/manilarome/lightdm-webkit2-theme-glorious

If the issue still persists, try setting your Pop OS power mode to hybrid with 
```sudo system76-power graphics hybrid```

**Comment by satyamurti** [comment]
The above solution worked thanks alot man :+1:
